# Generated by Django 4.0 on 2022-11-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_number', models.CharField(max_length=200)),
                ('animal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempretureTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_front_udder_quarter', models.FloatField()),
                ('left_front_udder_quarter', models.FloatField()),
                ('right_rear_udder_quarter', models.FloatField()),
                ('left_rear_udder_quarter', models.FloatField()),
                ('has_mastitis', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animal')),
            ],
        ),
        migrations.CreateModel(
            name='MilkTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductivity_lf', models.FloatField()),
                ('conductivity_lr', models.FloatField()),
                ('conductivity_rf', models.FloatField()),
                ('conductivity_rr', models.FloatField()),
                ('has_mastitis', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animal')),
            ],
        ),
    ]
