# Generated by Django 4.0 on 2022-11-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempreturetest',
            name='has_mastitis',
        ),
        migrations.CreateModel(
            name='TempretureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_front_udder_quarter', models.IntegerField()),
                ('left_front_udder_quarter', models.IntegerField()),
                ('right_rear_udder_quarter', models.IntegerField()),
                ('left_rear_udder_quarter', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tempreturetest')),
            ],
        ),
    ]
